name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./orderService/pom.xml
          mvn clean package -f ./deliveryService/pom.xml
          mvn clean package -f ./productService/pom.xml
          mvn clean package -f ./reviewService/pom.xml
          mvn clean package -f ./userService/pom.xml

      - name: Docker Build and push for OrderService
        uses: docker/build-push-action@v4
        with:
          context: ./orderService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/orderservice:latest
            ghcr.io/${{ github.repository }}/orderservice:${{ github.ref_name }}
            
      - name: Docker Build and push for DeliveryService
        uses: docker/build-push-action@v4
        with:
          context: ./deliveryService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/deliveryservice:latest
            ghcr.io/${{ github.repository }}/deliveryservice:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductService
        uses: docker/build-push-action@v4
        with:
          context: ./productService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/productservice:latest
            ghcr.io/${{ github.repository }}/productservice:${{ github.ref_name }}
            
      - name: Docker Build and push for ReviewService
        uses: docker/build-push-action@v4
        with:
          context: ./reviewService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reviewservice:latest
            ghcr.io/${{ github.repository }}/reviewservice:${{ github.ref_name }}
            
      - name: Docker Build and push for UserService
        uses: docker/build-push-action@v4
        with:
          context: ./userService
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/userservice:latest
            ghcr.io/${{ github.repository }}/userservice:${{ github.ref_name }}
            
