apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: hosunglee222/order:latest
          ports:
            - containerPort: 8080
