
server:
  port: 8088

---


keycloak-client:
  server-url: http://localhost:9090
  realm: master

spring:
  config:
    activate:
      on-profile: default
  cloud:
    gateway:
      default-filters:
        - TokenRelay 
      routes:
        - id: orderService
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**,  
        - id: deliveryService
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/**,  
        - id: productService
          uri: http://localhost:8084
          predicates:
            - Path=/products/**,  
        - id: reviewService
          uri: http://localhost:8085
          predicates:
            - Path=/reviews/**,  
        - id: userService
          uri: http://localhost:8086
          predicates:
            - Path=/users/**,  
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globals:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "gateway-path/login/oauth2/code/client-name"
            authorization-grant-type: authorization_code
            scope: openid
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

---

spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: orderService
          uri: http://orderService:8080
          predicates:
            - Path=/orders/** 
        - id: deliveryService
          uri: http://deliveryService:8080
          predicates:
            - Path=/deliveries/** 
        - id: productService
          uri: http://productService:8080
          predicates:
            - Path=/products/** 
        - id: reviewService
          uri: http://reviewService:8080
          predicates:
            - Path=/reviews/** 
        - id: userService
          uri: http://userService:8080
          predicates:
            - Path=/users/** 
      globals:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

server:
  port: 8080
