apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: hosunglee222/product:latest
          ports:
            - containerPort: 8080
